Object = require 'libraries/classic/classic'
-- Timer  = require 'libraries/hump/timer'
-- Camera = require 'libraries/hump/camera'
-- Vector = require 'libraries/hump/vector'
require 'utils'
require 'objects/GameObject'
require 'objects/Area'
require 'rooms/Stage'
require 'rooms/GameScene/GameScene'
require 'rooms/MainMenuScene/MainMenuScene'
require 'rooms/LevelScene/LevelScene'